# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en"
title                    : "Satarupa Guha"
title_separator          : "-"
name                     : "Satarupa Guha"
description              : "It is our choices, Harry, that show what we truly are, far more than our abilities."
url                      : https://satarupaguha11.github.io
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : satarupaguha11/satarupaguha11.github.io
breadcrumbs              : true
words_per_minute         : 200

# SEO Related
google_site_verification : 
bing_site_verification   : 

# Social Sharing
twitter:
  username               : "satarupaguha"
facebook:
  username               : "satarupa.guha"

# Site Author
author:
  name             : "Satarupa Guha"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "ML. NLP. Books. Music."
  location         : "Hyderabad, India"
  email            : "satarupaguha11@gmail.com"
  uri              : "https://satarupaguha11.github.io/"
  facebook         : "satarupa.guha"
  github           : "satarupaguha11"
  linkedin         : "satarupa-guha-3aa52a5b"
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
  twitter          : "satarupaguha"

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - backup/
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: true

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: nested # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata

# Plugins (previously gems:)
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Remote theme
remote_theme: "mmistakes/minimal-mistakes"

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
